# Generated by Django 4.2.3 on 2023-08-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_article_topicuser_comment_articletopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletopic',
            name='date_join',
        ),
    ]
