# Generated by Django 4.2.3 on 2023-08-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_remove_articletopic_date_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_topic',
        ),
        migrations.DeleteModel(
            name='ArticleTopic',
        ),
    ]
