# Generated by Django 4.2.3 on 2023-08-03 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contain',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(255)]),
        ),
    ]
