# Generated by Django 4.2.3 on 2023-08-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_alter_article_contain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contain',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='header',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='notification',
            new_name='message',
        ),
    ]
