# Generated by Django 4.2.3 on 2023-08-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_rename_contain_article_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicuser',
            old_name='notify_field',
            new_name='notify',
        ),
    ]
