# Generated by Django 4.2.3 on 2023-08-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_rename_notify_field_topicuser_notify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title', 'id']},
        ),
    ]
