# Generated by Django 4.2.3 on 2023-08-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
