# Generated by Django 4.2.3 on 2023-08-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_alter_article_title_alter_topic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicuser',
            old_name='topic_user',
            new_name='user',
        ),
    ]
