# Generated by Django 4.2.3 on 2023-08-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_rename_topic_user_topicuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
